### PR TITLE
Added Docker stack and AMF fixes for Flash preloader

### LINKED ISSUE #48: Dockerization
The title says it all.

### PR DESCRIPTION
**Pull request by jpfleischer**
Summary
- Add a Docker-based dev stack (app, MariaDB, Flash client via noVNC) and supporting tooling.
- Fix AMF bootstrap/preloader hangs by adding missing service stubs and aligning AMF DB config with env vars.
- Add crossdomain policies required by the legacy preloader.
- Add asset/supplement fetch + items import helpers and ignore large assets in git.
- Close #48.

Key Changes
- Docker/compose for reproducible setup and Flash client workflow.
- AMF: missing service stubs, config/env DB wiring, logger disabled to avoid fatal on permissions.
- Crossdomain: `crossdomain.xml` + `crossdomain1.xml`.
- Tooling: asset/supplement fetch script + `make` targets.

How to Test
- `docker compose build`
- `docker compose up -d`
- Run `make assets` and `make items` (if you want full item data)
  - should in the future remove the script and just wget it from Puccamite git repo
- Open `http://localhost:6080` and load `http://www.farmville.com/game` inside Basilisk.
- TEMPORARILY: Run `docker compose exec fv-replowed php artisan migrate --seed`

Notes
- This PR keeps debug hooks gated behind `/tmp/amf_debug` (off by default).

### CODE REVIEW

File: public/farmville/flashservices/amfphp/Functions/UserService.php [hunk 1]
```diff
@@ -93,32 +133,28 @@ public static function getMOTD(){
...
-
-            // Add the next one
-            $flags[$toAdd] = true;
-            $flags = serialize($flags);
-            $stmt = $conn->prepare("UPDATE usermeta SET seenFlags = ? WHERE uid = ?");
-            $stmt->bind_param("ss", $flags, $uid);
-            $stmt->execute();
-            $db->destroy();
-        }
+        // Let's get our current seenFlags
```
Comment (PuccamiteTech) [inline public/farmville/flashservices/amfphp/Functions/UserService.php]: this overwrites the newer sanitized changes with the originals, setseenflag should be updated to use the newer stuff

**Comment by PuccamiteTech** [comment]
In non-Dockerized environments, updates to the db are broken entirely when it comes to coins, etc.

**Comment by PuccamiteTech** [comment]
The `docker compose exec fv-replowed php artisan migrate --seed` command is not running automatically. Is the database started when you run it at first?

**Comment by PuccamiteTech** [comment]
> > make build should be moved after make assets because the .dockerignore file doesn't take effect
> 
> i believe this is already true

My bad, I meant to say, you should run make build BEFORE make assets as it is in the readme, otherwise it attempts to include them in the image

**Comment by PuccamiteTech** [comment]
arget fv-replowed: failed to solve: ResourceExhausted: failed to copy files: userspace copy failed: write /var/www/html/.cache/fv-assets/urls-bluepload.unstable.life-farmvilleassets.txt-shallow-20201225-045045-5762m-00001.warc.gz: no space left on device

The .cache directory should be ignored in .dockerignore.

**Comment by PuccamiteTech** [comment]
merging to testing soon
